# common PostgreSQL database settings
common: &common
  host:     localhost
  adapter:  postgresql
  encoding: unicode
  username: postgres
  password: 4242424242
  timeout:  5000
  pool:     5

development:
  <<:       *common
  database: personal_website_development

test:
  <<:       *common
  database: personal_website_test

production:
  <<:       *common
  database: personal_website_production